services:
  # ==============================================
  # TRAEFIK - REVERSE PROXY
  # ==============================================
  traefik:
    image: traefik:v3.0
    container_name: nebu-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9080:9080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./gateway/traefik.simple.yml:/etc/traefik/traefik.yml:ro
      - ./gateway/letsencrypt:/letsencrypt:rw
      - traefik_logs:/logs:rw
    networks:
      - traefik-network
      - nebu-network
    environment:
      - DOMAIN=${DOMAIN:-flow-telligence.com}
      - ACME_EMAIL=${ACME_EMAIL:-admin@flow-telligence.com}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-flow-telligence.com}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9080/ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  # ==============================================
  # FRONTEND - NEBU WEBSITE (REMIX)
  # ==============================================
  frontend:
    build:
      context: ../nebu-website
      dockerfile: Dockerfile
      target: production
    container_name: nebu-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_URL=https://flow-telligence.com
      - API_URL=https://62.169.30.44/api
      - SESSION_SECRET=${SESSION_SECRET:-your_session_secret_change_in_production_2024}
    volumes:
      - frontend_uploads:/app/public/uploads
    networks:
      - traefik-network
      - nebu-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      
      # Router principal para el dominio
      - "traefik.http.routers.frontend-secure.rule=Host(`flow-telligence.com`) || Host(`www.flow-telligence.com`)"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-secure.service=frontend"
      
      # Router para acceso directo por IP puerto 8080
      - "traefik.http.routers.frontend-ip.rule=Host(`62.169.30.44`)"
      - "traefik.http.routers.frontend-ip.entrypoints=websecure-8080"
      - "traefik.http.routers.frontend-ip.tls=true"
      - "traefik.http.routers.frontend-ip.service=frontend"
      
      # Servicio
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      
      # Middlewares para seguridad
      - "traefik.http.middlewares.frontend-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend-secure.middlewares=frontend-headers"
      - "traefik.http.routers.frontend-ip.middlewares=frontend-headers"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - traefik

volumes:
  frontend_uploads:
    driver: local
  traefik_logs:
    driver: local

networks:
  traefik-network:
    driver: bridge
  nebu-network:
    driver: bridge
