import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ProductCatalog } from '../entities/product-catalog.entity';

@Injectable()
export class ProductSeedService {
  private readonly logger = new Logger(ProductSeedService.name);

  constructor(
    @InjectRepository(ProductCatalog)
    private readonly productRepository: Repository<ProductCatalog>,
  ) {}

  async seedProducts() {
    const products = [
      {
        slug: 'star-hunters',
        name: 'Star Hunters',
        concept: 'Idol Warriors',
        originalCharacter: 'KPop Demon Hunters (Rumi, Mira, Zoey)',
        description: 'Grupo de 3 chicas idol que luchan contra monstruos. Estética K-pop con poderes mágicos',
        shortDescription: 'Trio de chicas idol con poderes mágicos',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '6-12 años',
        features: ['Estética K-pop', 'Poderes mágicos', 'Set de 3 personajes'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'chaos-cat',
        name: 'Chaos Cat',
        concept: 'Loco Felino',
        originalCharacter: 'Derpy Tiger',
        description: 'Criatura felina torpe y caótica del "otro mundo", personalidad traviesa',
        shortDescription: 'Felino travieso del otro mundo',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '4-10 años',
        features: ['Personalidad traviesa', 'Diseño caótico', 'Pelaje suave'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'kosmik',
        name: 'Kosmik',
        concept: 'Alien Travieso',
        originalCharacter: 'Stitch (Experimento 626)',
        description: 'Criatura alienígena azul/morada con orejas grandes, destructiva pero adorable',
        shortDescription: 'Alien adorable y travieso',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'blue', name: 'Azul', hex: '#4A90E2' },
          { id: 'purple', name: 'Morado', hex: '#A78BFA' },
        ],
        ageRange: '4-10 años',
        features: ['Orejas grandes', 'Adorablemente destructivo', 'Colores vibrantes'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'sky-pup',
        name: 'Sky Pup',
        concept: 'Cachorro Azulito',
        originalCharacter: 'Bluey',
        description: 'Perrito de color único (turquesa, lavanda) con familia adorable',
        shortDescription: 'Cachorro colorido y familiar',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'turquoise', name: 'Turquesa', hex: '#4ECDC4' },
          { id: 'lavender', name: 'Lavanda', hex: '#A78BFA' },
        ],
        ageRange: '3-8 años',
        features: ['Colores únicos', 'Temática familiar', 'Super suave'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'gruñoncito',
        name: 'Gruñoncito',
        concept: 'Monstruito Dientón',
        originalCharacter: 'Labubu',
        description: 'Criatura pequeña con dientes puntiagudos, estética "ugly-cute"',
        shortDescription: 'Monstruito adorablemente feo',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '6-12 años',
        features: ['Estética ugly-cute', 'Dientes puntiagudos', 'Pequeño y coleccionable'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'long-arms',
        name: 'Long Arms',
        concept: 'Abrazador',
        originalCharacter: 'Huggy Wuggy',
        description: 'Criatura alta y peluda con brazos largos, sonrisa inquietante pero amigable',
        shortDescription: 'Criatura de brazos largos y amigable',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '8-14 años',
        features: ['Brazos extra largos', 'Pelaje suave', 'Diseño único'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'sleepy-kitty',
        name: 'Sleepy Kitty',
        concept: 'Soñolín',
        originalCharacter: 'CatNap (Smiling Critters)',
        description: 'Gato morado/lavanda que ayuda a dormir, temática de sueños',
        shortDescription: 'Gatito que ayuda a dormir',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'purple', name: 'Morado', hex: '#9B59B6' },
          { id: 'lavender', name: 'Lavanda', hex: '#C8A2C8' },
        ],
        ageRange: '3-10 años',
        features: ['Ayuda a dormir', 'Super suave', 'Temática de sueños'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'sunny-pup',
        name: 'Sunny Pup',
        concept: 'Sol Canino',
        originalCharacter: 'DogDay',
        description: 'Perro amarillo/naranja alegre, temática de día soleado',
        shortDescription: 'Perrito alegre y soleado',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'yellow', name: 'Amarillo', hex: '#F1C40F' },
          { id: 'orange', name: 'Naranja', hex: '#E67E22' },
        ],
        ageRange: '3-10 años',
        features: ['Súper alegre', 'Colores vibrantes', 'Temática diurna'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'pixel-jester',
        name: 'Pixel Jester',
        concept: 'Arlequina Digital',
        originalCharacter: 'Pomni (Digital Circus)',
        description: 'Payasita/bufona en mundo digital, colores brillantes, ansiosa pero valiente',
        shortDescription: 'Arlequina digital valiente',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '8-14 años',
        features: ['Estética digital', 'Colores brillantes', 'Personalidad compleja'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'purple-bunny',
        name: 'Purple Bunny',
        concept: 'Conejo Sarcástico',
        originalCharacter: 'Jax (Digital Circus)',
        description: 'Conejo morado con actitud rebelde y humor negro',
        shortDescription: 'Conejo rebelde y sarcástico',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'purple', name: 'Morado', hex: '#8B7CCF' },
        ],
        ageRange: '10-16 años',
        features: ['Actitud rebelde', 'Humor negro', 'Diseño cool'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'sawbite',
        name: 'Sawbite',
        concept: 'Motor Pup / Buzz Buddy',
        originalCharacter: 'Pochita (Chainsaw Man)',
        description: 'Perrito/criatura naranja redonda con algo mecánico en la cabeza (engranaje, hélice, tornillo), cola con asa, boca con cierre/cremallera',
        shortDescription: 'Perrito mecánico adorable',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'orange', name: 'Naranja', hex: '#FF6B35' },
        ],
        ageRange: '10-16 años',
        features: ['Diseño mecánico', 'Cola con asa', 'Boca cremallera'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'dark-bunny',
        name: 'Dark Bunny',
        concept: 'Goth Rabbit',
        originalCharacter: 'Kuromi',
        description: 'Conejita gótica con capucha negra, actitud punk pero tierna',
        shortDescription: 'Conejita gótica y tierna',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [],
        ageRange: '6-14 años',
        features: ['Estilo gótico', 'Capucha negra', 'Actitud punk'],
        category: 'plushie',
        active: true,
      },
      {
        slug: 'sweet-bunny',
        name: 'Sweet Bunny',
        concept: 'Conejita Rosa',
        originalCharacter: 'My Melody',
        description: 'Conejita rosa con capucha, dulce y tierna',
        shortDescription: 'Conejita dulce y adorable',
        price: 380,
        depositAmount: 190,
        preOrder: true,
        inStock: false,
        stockCount: 0,
        images: [],
        colors: [
          { id: 'pink', name: 'Rosa', hex: '#FFC0CB' },
        ],
        ageRange: '4-12 años',
        features: ['Super dulce', 'Capucha adorable', 'Color rosa suave'],
        category: 'plushie',
        active: true,
      },
    ];

    for (const productData of products) {
      const existing = await this.productRepository.findOne({
        where: { slug: productData.slug },
      });

      if (!existing) {
        const product = this.productRepository.create(productData);
        await this.productRepository.save(product);
        this.logger.log(`✅ Created product: ${productData.name}`);
      } else {
        this.logger.log(`⏭️  Product already exists: ${productData.name}`);
      }
    }

    this.logger.log('✅ Product seed completed!');
  }
}
