import { DataSource } from 'typeorm';
import { Logger } from '@nestjs/common';
import { ProductCatalog } from '../../toys/entities/product-catalog.entity';

/**
 * Product Catalog Seeder
 *
 * Este seeder inserta 15 productos iniciales en el catálogo, incluyendo Nebu Dino y Nebu Capibara.
 * Solo ejecuta si la tabla está vacía.
 *
 * Uso:
 *   npm run seed:products
 */
export async function seedProducts(dataSource: DataSource): Promise<void> {
  const logger = new Logger('ProductSeeder');
  const productRepository = dataSource.getRepository(ProductCatalog);

  // Verificar si ya hay productos
  const count = await productRepository.count();
  if (count > 0) {
    logger.warn(`Ya existen ${count} productos. Saltando seed inicial.`);
    return;
  }

  logger.log('🌱 Insertando 15 productos iniciales...');

  const products = [
    {
      slug: 'nebu-dino',
      name: 'Nebu Dino',
      concept: '🦕 Nebu Dinosaurio',
      originalCharacter: 'Nebu',
      description: 'El peluche inteligente con IA que acompaña y enseña a los más pequeños. Nebu Dino es tu compañero de aprendizaje y aventuras, diseñado para niños de 4 a 12 años.',
      shortDescription: 'Peluche inteligente con IA conversacional, sin pantallas, educativo y súper entretenido',
      price: 380.0,
      depositAmount: 190.0,
      inStock: true,
      stockCount: 20,
      preOrder: true,
      images: [
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/dino_0/public',
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/dino_1/public',
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/dino_2/public'
      ],
      colors: [
        { id: 'rosa', name: 'Rosa', hex: '#FF69B4', gradient: 'from-pink-400 to-rose-500' },
        { id: 'verde', name: 'Verde', hex: '#90EE90', gradient: 'from-green-400 to-emerald-500' },
        { id: 'azul', name: 'Azul', hex: '#87CEEB', gradient: 'from-sky-400 to-blue-500' }
      ], // Rosa, Verde, Azul
      features: [
        'IA personalizada adaptada a cada niño',
        'Conversaciones educativas ilimitadas',
        'Sin pantallas, 100% interactivo por voz',
        'App para padres con control parental',
        'Batería recargable 8-10 horas',
        'Actualizaciones de contenido continuas',
        'WiFi integrado',
        'Multiidioma (Español/Inglés)'
      ],
      category: 'smart-companions',
      badge: 'bestseller',
      active: true,
    },
    {
      slug: 'nebu-capibara',
      name: 'Nebu Capibara',
      concept: '🦦 Nebu Capibara',
      originalCharacter: 'Nebu',
      description: 'El peluche inteligente con IA que acompaña y enseña a los más pequeños. Nebu Capibara es tu compañero tranquilo y sabio, diseñado para niños de 4 a 12 años.',
      shortDescription: 'Peluche inteligente con IA conversacional, sin pantallas, educativo y súper relajante',
      price: 380.0,
      depositAmount: 190.0,
      inStock: true,
      stockCount: 15,
      preOrder: true,
      images: [
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/capibara_0/public',
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/capibara_1/public',
        'https://imagedelivery.net/MYEKC5pvgdAkEdXGy8suoQ/capibara_2/public'
      ],
      colors: [
        { id: 'marron', name: 'Marrón', hex: '#8B7355', gradient: 'from-amber-700 to-orange-800' },
        { id: 'beige', name: 'Beige', hex: '#A0826D', gradient: 'from-stone-400 to-stone-600' },
        { id: 'camel', name: 'Camel', hex: '#C19A6B', gradient: 'from-orange-300 to-amber-500' }
      ], // Marrón, Beige, Camel
      features: [
        'IA personalizada adaptada a cada niño',
        'Conversaciones educativas ilimitadas',
        'Sin pantallas, 100% interactivo por voz',
        'App para padres con control parental',
        'Batería recargable 8-10 horas',
        'Actualizaciones de contenido continuas',
        'WiFi integrado',
        'Multiidioma (Español/Inglés)'
      ],
      category: 'smart-companions',
      badge: 'new',
      active: true,
    },
    {
      slug: 'star-hunters',
      name: 'Star Hunters',
      concept: '🌟 Cazadores de Estrellas',
      originalCharacter: 'Nebu Original',
      description: 'Aventureros cósmicos que viajan entre galaxias',
      shortDescription: 'Aventureros cósmicos con traje espacial LED y mochila de propulsión',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#FF6B9D', '#4A90E2', '#FFD700'],
      features: ['Traje espacial con luces LED', 'Mochila de propulsión removible'],
      category: 'space-adventure',
      badge: 'new',
      active: true,
    },
    {
      slug: 'chaos-cat',
      name: 'Chaos Cat',
      concept: '🐱 Gato del Caos',
      originalCharacter: 'Nebu Original',
      description: 'Un felino travieso del multiverso',
      shortDescription: 'Felino travieso del multiverso con detalles holográficos brillantes',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#9B59B6', '#E74C3C', '#F39C12'],
      features: ['Pelaje suave con detalles holográficos', 'Ojos con brillo nocturno'],
      category: 'fantasy-creatures',
      badge: 'hot',
      active: true,
    },
    {
      slug: 'kosmik',
      name: 'Kosmik',
      concept: '🌌 Guardián Cósmico',
      originalCharacter: 'Nebu Original',
      description: 'Protector de las dimensiones',
      shortDescription: 'Guardián cósmico con alas holográficas y acabado metalizado',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#6C5CE7', '#A29BFE', '#74B9FF'],
      features: ['Alas con efecto holográfico', 'Cuerpo con acabado metalizado'],
      category: 'space-adventure',
      badge: 'exclusive',
      active: true,
    },
    {
      slug: 'sky-pup',
      name: 'Sky Pup',
      concept: '🐕 Cachorro Volador',
      originalCharacter: 'Nebu Original',
      description: 'Un adorable cachorro con alas esponjosas',
      shortDescription: 'Adorable cachorro con alas extra suaves y collar con campana',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#87CEEB', '#FFB6C1', '#FFFFFF'],
      features: ['Alas de peluche extra suaves', 'Collar con campana sonora'],
      category: 'cute-companions',
      badge: 'new',
      active: true,
    },
    {
      slug: 'grunoncito',
      name: 'Gruñoncito',
      concept: '😾 Pequeño Gruñón',
      originalCharacter: 'Nebu Original',
      description: 'Este pequeño tiene cara de pocos amigos',
      shortDescription: 'Pequeño gruñón con expresión única y pelaje texturizado realista',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#8B7355', '#D2691E', '#F5DEB3'],
      features: ['Expresión facial única', 'Pelaje texturizado realista'],
      category: 'funny-friends',
      badge: 'hot',
      active: true,
    },
    {
      slug: 'long-arms',
      name: 'Long Arms',
      concept: '🦾 Brazos Largos',
      originalCharacter: 'Nebu Original',
      description: 'Criatura peculiar con extremidades extensibles',
      shortDescription: 'Criatura peculiar con brazos articulados y manos flexibles',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#20B2AA', '#48D1CC', '#E0FFFF'],
      features: ['Brazos articulados', 'Manos con dedos flexibles'],
      category: 'funny-friends',
      badge: 'new',
      active: true,
    },
    {
      slug: 'sleepy-kitty',
      name: 'Sleepy Kitty',
      concept: '😴 Gatito Somnoliento',
      originalCharacter: 'Nebu Original',
      description: 'Un adorable gatito en busca del lugar perfecto',
      shortDescription: 'Gatito somnoliento con almohada incluida y ojos semicerrados',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#FFB6C1', '#E6E6FA', '#FFFFFF'],
      features: ['Incluye almohada', 'Ojos semicerrados'],
      category: 'cute-companions',
      badge: 'hot',
      active: true,
    },
    {
      slug: 'sunny-pup',
      name: 'Sunny Pup',
      concept: '☀️ Cachorro Solar',
      originalCharacter: 'Nebu Original',
      description: 'Un cachorro radiante que lleva el sol',
      shortDescription: 'Cachorro radiante con pelaje brillante y rayos solares removibles',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#FFD700', '#FFA500', '#FF6347'],
      features: ['Pelaje con efecto brillante', 'Rayos solares removibles'],
      category: 'space-adventure',
      badge: 'exclusive',
      active: true,
    },
    {
      slug: 'pixel-jester',
      name: 'Pixel Jester',
      concept: '🎮 Bufón de Píxeles',
      originalCharacter: 'Nebu Original',
      description: 'Personaje saltado de un videojuego retro',
      shortDescription: 'Bufón de píxeles retro con diseño inspirado en videojuegos clásicos',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#FF00FF', '#00FFFF', '#FFFF00'],
      features: ['Diseño inspirado en gráficos retro', 'Detalles pixelados'],
      category: 'gaming-heroes',
      badge: 'new',
      active: true,
    },
    {
      slug: 'purple-bunny',
      name: 'Purple Bunny',
      concept: '🐰 Conejito Púrpura',
      originalCharacter: 'Nebu Original',
      description: 'Un conejo místico de un bosque encantado',
      shortDescription: 'Conejo místico con orejas extra largas y pelaje nacarado',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#9370DB', '#BA55D3', '#DDA0DD'],
      features: ['Orejas extra largas', 'Pelaje con brillo nacarado'],
      category: 'fantasy-creatures',
      badge: 'hot',
      active: true,
    },
    {
      slug: 'sawbite',
      name: 'Sawbite',
      concept: '🦷 Mordisco Aserrado',
      originalCharacter: 'Nebu Original',
      description: 'Una criatura marina con dientes afilados',
      shortDescription: 'Criatura marina con mandíbula articulada y dientes de goma suave',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#4682B4', '#5F9EA0', '#B0C4DE'],
      features: ['Mandíbula articulada', 'Dientes de goma suave'],
      category: 'ocean-buddies',
      badge: 'exclusive',
      active: true,
    },
    {
      slug: 'dark-bunny',
      name: 'Dark Bunny',
      concept: '🌑 Conejito Oscuro',
      originalCharacter: 'Nebu Original',
      description: 'El hermano misterioso del Purple Bunny',
      shortDescription: 'Conejito misterioso con pelaje aterciopelado y ojos con brillo rojo',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#2F4F4F', '#36454F', '#708090'],
      features: ['Pelaje negro aterciopelado', 'Ojos con brillo rojo'],
      category: 'fantasy-creatures',
      badge: 'new',
      active: true,
    },
    {
      slug: 'sweet-bunny',
      name: 'Sweet Bunny',
      concept: '🍬 Conejito Dulce',
      originalCharacter: 'Nebu Original',
      description: 'Un conejito hecho de algodón de azúcar',
      shortDescription: 'Conejito de algodón de azúcar con textura suave y aroma a vainilla',
      price: 380.0,
      depositAmount: 190.0,
      inStock: false,
      preOrder: true,
      images: [],
      colors: ['#FFB6D9', '#FFC0CB', '#FFDDF4'],
      features: ['Textura de algodón de azúcar', 'Aroma a vainilla'],
      category: 'cute-companions',
      badge: 'hot',
      active: true,
    },
  ];

  // Insertar productos
  const productEntities = products.map((data) => productRepository.create(data));
  await productRepository.save(productEntities);

  logger.log('✅ 15 productos insertados exitosamente (incluyendo Nebu Dino y Nebu Capibara)');
}
